[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    
    "@openzeppelin/contracts=lib/forge-std/@openzeppelin/contracts",
    "@chainlink/contracts=lib/forge-std/@chainlink/contracts"
    
]

[invariant]

runs = 128
depth = 128
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
